#!/usr/bin/env python3
# Binds infra/k8s/monitoring-app.yaml's OCI digest to the pinned chart (through the manifest the
# install script fetches by that digest), renders the chart with exactly the Application's
# valuesObject, as Argo CD does (release monitoring, CRDs included), and checks the lean stack: only kinds and names the finrisk-monitoring AppProject permits, nothing exposed or
# persistent, images by digest, Pod Security restricted, and the Prometheus hardening (signal reload,
# so no lifecycle API; ServiceMonitors confined). Every property is also checked against a
# deliberately broken copy of the values and must fail there. The Prometheus Pod itself is
# generated by the operator in the cluster, not here; the bootstrap checks it live. It needs the
# tools .github/scripts/install-k8s-tools.sh installs into $K8S_TOOLS, so it is not named
# test_*.py; terraform-validate.yml runs it after the install.
import copy
import hashlib
import json
from collections import Counter
from fnmatch import fnmatchcase

import yaml

from k8s_tools import (DIGEST, HELM, MONITORING_CHART, MONITORING_MANIFEST, PINS, containers, manifest, monitoring, pod_templates,
                       report, require, run)
from pod_security import restricted

require("Monitoring stack acceptance")
APP = manifest("monitoring-app.yaml")[0]
VALUES = APP["spec"]["source"]["helm"]["valuesObject"]
PROJECT = next(p for p in manifest("argocd-projects.yaml") if p["metadata"]["name"] == APP["spec"]["project"])
# The OCI manifest Argo CD syncs, fetched by its digest (the install script checks its sha256).
OCI_BYTES = MONITORING_MANIFEST.read_bytes()
CLUSTER_SCOPED = {"CustomResourceDefinition", "ClusterRole", "ClusterRoleBinding", "Namespace", "PersistentVolume",
                  "ValidatingWebhookConfiguration", "MutatingWebhookConfiguration", "PriorityClass", "StorageClass"}
KINDS = Counter({"CustomResourceDefinition": 10, "ServiceAccount": 3, "ClusterRole": 3, "ClusterRoleBinding": 3,
                 "Service": 3, "Deployment": 2, "ServiceMonitor": 3, "Prometheus": 1})


def group(doc):
    return doc["apiVersion"].rpartition("/")[0]


def permitted(doc):
    """Argo CD's AppProject rule: namespaced kinds by group and kind, cluster-scoped ones by name glob too."""
    spec = PROJECT["spec"]
    if doc["kind"] in CLUSTER_SCOPED:
        return any(i["group"] == group(doc) and i["kind"] == doc["kind"]
                   and fnmatchcase(doc["metadata"]["name"], i.get("name") or "*") for i in spec["clusterResourceWhitelist"])
    namespace = doc["metadata"].get("namespace") or APP["spec"]["destination"]["namespace"]
    return {"group": group(doc), "kind": doc["kind"]} in spec["namespaceResourceWhitelist"] \
        and any(d["namespace"] == namespace for d in spec["destinations"])


def arg(container, name):
    return next((a.split("=", 1)[1] for a in container.get("args") or [] if a.startswith(f"--{name}=")), None)


def properties(docs):
    by = {(d["kind"], d["metadata"]["name"]): d for d in docs}
    templates = pod_templates(docs)
    every = [c for _, _, t in templates for c in containers(t)]
    operator = next((c for kind, name, t in templates if name == "monitoring-operator" for c in containers(t)), {})
    prometheus = (by.get(("Prometheus", "monitoring")) or {}).get("spec", {})
    services = [d for d in docs if d["kind"] == "Service"]
    ksm_role = (by.get(("ClusterRole", "monitoring-kube-state-metrics")) or {}).get("rules") or []
    ksm_monitor = (by.get(("ServiceMonitor", "monitoring-kube-state-metrics")) or {}).get("spec", {})
    ksm_service = by.get(("Service", "monitoring-kube-state-metrics")) or {"metadata": {}}
    reloader = [arg(operator, f"config-reloader-{r}") for r in ("cpu-request", "memory-request", "memory-limit")]
    hooked = [d for d in docs if "helm.sh/hook" in (d["metadata"].get("annotations") or {})]
    return {
        "renders": bool(docs),
        "kinds: 10 CRDs, ServiceAccounts, ClusterRoles and bindings, Services, Deployments, ServiceMonitors, Prometheus":
            Counter(d["kind"] for d in docs) == KINDS,
        "every object fits the finrisk-monitoring AppProject (kind, cluster-scoped name, destination)": bool(docs)
            and all(permitted(d) for d in docs),
        "no Helm hooks, Jobs, PersistentVolumeClaims or volumeClaimTemplates": not hooked
            and not {"Job", "CronJob", "PersistentVolumeClaim"} & {d["kind"] for d in docs}
            and "volumeClaimTemplate" not in json.dumps(prometheus.get("storage", {})),
        "Services ClusterIP only, without externalIPs": len(services) == 3
            and all(s["spec"].get("type", "ClusterIP") == "ClusterIP" and not s["spec"].get("externalIPs") for s in services),
        "Prometheus keeps its data in a size-limited emptyDir": prometheus.get("storage") == {"emptyDir": {"sizeLimit": "1Gi"}},
        # The operator adds --web.enable-lifecycle only for the HTTP strategy (the bootstrap checks the
        # generated StatefulSet as well).
        "Prometheus reloads by signal, so the operator leaves the lifecycle API off":
            prometheus.get("reloadStrategy") == "ProcessSignal" and prometheus.get("enableAdminAPI") is False,
        "ServiceMonitors cannot read Prometheus's files or reach beyond their own namespace":
            prometheus.get("arbitraryFSAccessThroughSMs") == {"deny": True} and prometheus.get("ignoreNamespaceSelectors") is True,
        "every ServiceMonitor in finrisk and monitoring is selected, whatever its labels":
            prometheus.get("serviceMonitorSelector") == {} and prometheus.get("serviceMonitorNamespaceSelector") == {
                "matchExpressions": [{"key": "kubernetes.io/metadata.name", "operator": "In", "values": ["finrisk", "monitoring"]}]},
        "every image by digest, the operator's config-reloader and Thanos defaults included": bool(every) and all(
            DIGEST.fullmatch(i or "") for i in [c["image"] for c in every] + [prometheus.get("image"),
                                                 arg(operator, "prometheus-config-reloader"), arg(operator, "thanos-default-base-image")]),
        "Deployments meet Pod Security restricted": len(templates) == 2 and all(all(restricted(t).values()) for _, _, t in templates),
        "operator TLS off with its admission webhooks off": arg(operator, "web.enable-tls") == "false"
            and not {"ValidatingWebhookConfiguration", "MutatingWebhookConfiguration", "Secret"} & {d["kind"] for d in docs},
        "the operator manages no kubelet Service in kube-system": operator.get("args") is not None
            and arg(operator, "kubelet-service") is None,
        "kube-state-metrics reads no Secrets or ConfigMaps": bool(ksm_role) and not {"secrets", "configmaps"}
            & {r for rule in ksm_role for r in rule.get("resources", [])},
        # Prometheus "monitoring" is StatefulSet prometheus-monitoring; the bootstrap reads both names.
        "names the bootstrap and the deploy evidence use": ("Prometheus", "monitoring") in by
            and [p["port"] for p in (by.get(("Service", "monitoring-prometheus")) or {"spec": {}})["spec"].get("ports", [])][:1] == [9090]
            and ksm_monitor.get("selector", {}).get("matchLabels", {"x": "y"}).items() <= (ksm_service["metadata"].get("labels") or {}).items(),
        "requests and memory limits on every container, Prometheus and its config reloader included": bool(every) and all(
            {"cpu", "memory"} <= set((c.get("resources") or {}).get("requests") or {})
            and "memory" in ((c.get("resources") or {}).get("limits") or {}) for c in every)
            and {"cpu", "memory"} <= set(prometheus.get("resources", {}).get("requests", {}))
            and "memory" in prometheus.get("resources", {}).get("limits", {}) and all(v not in (None, "0") for v in reloader),
    }


def oci_properties(target, manifest_bytes):
    oci = json.loads(manifest_bytes)
    layers = [l["digest"] for l in oci.get("layers", []) if l["mediaType"] == "application/vnd.cncf.helm.chart.content.v1.tar+gzip"]
    return {
        "the Application's targetRevision is the digest of the OCI manifest fetched by it":
            target == "sha256:" + hashlib.sha256(manifest_bytes).hexdigest() == "sha256:" + PINS.get("KUBE_PROMETHEUS_STACK_MANIFEST_SHA256", ""),
        "that manifest is a Helm chart of the pinned version, whose one chart layer is the pinned tgz":
            oci.get("config", {}).get("mediaType") == "application/vnd.cncf.helm.config.v1+json"
            and (oci.get("annotations") or {}).get("org.opencontainers.image.version") == PINS.get("KUBE_PROMETHEUS_STACK_VERSION")
            and layers == ["sha256:" + PINS.get("KUBE_PROMETHEUS_STACK_SHA256", "")]
            and hashlib.sha256(MONITORING_CHART.read_bytes()).hexdigest() == PINS.get("KUBE_PROMETHEUS_STACK_SHA256"),
    }


def other_layer(manifest_bytes):
    oci = json.loads(manifest_bytes)
    for layer in oci["layers"]:
        layer["digest"] = "sha256:" + "0" * 64
    return json.dumps(oci).encode()


OCI_CONTROLS = {  # (targetRevision, manifest bytes), the property that must fail
    "a targetRevision of another digest": (("sha256:" + "0" * 64, OCI_BYTES),
                                           "the Application's targetRevision is the digest of the OCI manifest fetched by it"),
    "a manifest whose chart layer is another tgz": ((None, other_layer(OCI_BYTES)),
                                                    "that manifest is a Helm chart of the pinned version, whose one chart layer is the pinned tgz"),
}


def broken(change):
    values = copy.deepcopy(VALUES)
    change(values)
    return values


def spec(v):
    return v["prometheus"]["prometheusSpec"]


CONTROLS = {
    "the operator image by tag only": (lambda v: v["prometheusOperator"]["image"].update(sha=""),
                                       "every image by digest, the operator's config-reloader and Thanos defaults included"),
    "the kube-state-metrics digest without its sha256: prefix": (
        lambda v: v["kube-state-metrics"]["image"].update(sha=v["kube-state-metrics"]["image"]["sha"].split(":")[1]),
        "every image by digest, the operator's config-reloader and Thanos defaults included"),
    "the Thanos default image by tag only": (lambda v: v["prometheusOperator"]["thanosImage"].update(sha=""),
                                             "every image by digest, the operator's config-reloader and Thanos defaults included"),
    "operator TLS on with its webhooks off": (lambda v: v["prometheusOperator"]["tls"].update(enabled=True),
                                              "operator TLS off with its admission webhooks off"),
    "Alertmanager enabled": (lambda v: v["alertmanager"].update(enabled=True),
                             "every object fits the finrisk-monitoring AppProject (kind, cluster-scoped name, destination)"),
    "the Prometheus token Secret": (lambda v: v["prometheus"]["serviceAccount"].update(createTokenSecret=True),
                                    "every object fits the finrisk-monitoring AppProject (kind, cluster-scoped name, destination)"),
    "the HTTP reload strategy (lifecycle API on)": (lambda v: spec(v).pop("reloadStrategy"),
                                                    "Prometheus reloads by signal, so the operator leaves the lifecycle API off"),
    "ServiceMonitors allowed to read files": (lambda v: spec(v).update(arbitraryFSAccessThroughSMs={"deny": False}),
                                              "ServiceMonitors cannot read Prometheus's files or reach beyond their own namespace"),
    "ServiceMonitor namespace selectors honoured": (lambda v: spec(v).update(ignoreNamespaceSelectors=False),
                                                    "ServiceMonitors cannot read Prometheus's files or reach beyond their own namespace"),
    "ServiceMonitors from every namespace": (lambda v: spec(v).pop("serviceMonitorNamespaceSelector"),
                                             "every ServiceMonitor in finrisk and monitoring is selected, whatever its labels"),
    "a PersistentVolumeClaim template": (lambda v: spec(v).update(storageSpec={"volumeClaimTemplate": {"spec": {
        "resources": {"requests": {"storage": "1Gi"}}}}}), "Prometheus keeps its data in a size-limited emptyDir"),
    "a LoadBalancer Prometheus Service": (lambda v: v["prometheus"].update(service={"type": "LoadBalancer"}),
                                          "Services ClusterIP only, without externalIPs"),
    "the kubelet Service": (lambda v: v["prometheusOperator"]["kubeletService"].update(enabled=True),
                            "the operator manages no kubelet Service in kube-system"),
    "kube-state-metrics' default collectors": (lambda v: v["kube-state-metrics"].pop("collectors"),
                                               "kube-state-metrics reads no Secrets or ConfigMaps"),
    "the chart's default names": (lambda v: v.pop("fullnameOverride"), "names the bootstrap and the deploy evidence use"),
    "Prometheus without resources": (lambda v: spec(v).pop("resources"),
                                     "requests and memory limits on every container, Prometheus and its config reloader included"),
}

_, docs = monitoring(VALUES)
found = properties(docs)
chart = yaml.safe_load(run(HELM, "show", "chart", MONITORING_CHART).stdout or "{}") or {}
found_oci = oci_properties(APP["spec"]["source"]["targetRevision"], OCI_BYTES)
checks = {
    **found_oci,
    "chart version is the pin, and its operator is the release the ServiceMonitor schema comes from":
        chart.get("version") == PINS.get("KUBE_PROMETHEUS_STACK_VERSION")
        and chart.get("appVersion") == PINS.get("PROMETHEUS_OPERATOR_VERSION"),
    **found,
}
for name, ((target, data), prop) in OCI_CONTROLS.items():
    checks[f"negative control: {name} fails '{prop}'"] = found_oci[prop] and not oci_properties(
        target or APP["spec"]["source"]["targetRevision"], data)[prop]
for name, (change, prop) in CONTROLS.items():
    _, mutated = monitoring(broken(change))
    checks[f"negative control: {name} fails '{prop}'"] = bool(mutated) and found[prop] and not properties(mutated)[prop]

report("Monitoring stack acceptance", checks)
